# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- develop
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Docker@2
  displayName: Docker_Login
  inputs:
    containerRegistry: 'dockerhub_login'
    command: 'login'
    addPipelineData: false
    addBaseImageData: false

- task: Docker@2
  displayName: Docker_Build_Push_'$(Build.BuildNumber)'
  inputs:
    containerRegistry: 'dockerhub_login'
    repository: 'dockernaveensddp/azuredocker'
    command: 'buildAndPush'
    Dockerfile: '**/AzureDockerfile'
    addPipelineData: false
    addBaseImageData: false


- task: ECRPushImage@1
  inputs:
    awsCredentials: 'AWS_CREDENTIALS'
    regionName: 'us-east-1'
    imageSource: 'imagename'
    sourceImageName: 'dockernaveensddp/azuredocker'
    sourceImageTag: '$(Build.BuildId)'
    outputVariable: 'CONTAINERIMAGEURL'
    repositoryName: 'automation'