# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- develop
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Docker@2
  displayName: Docker_Login
  inputs:
    containerRegistry: 'dockerhub_login'
    command: 'login'
    addPipelineData: false
    addBaseImageData: false
- task: Docker@2
  displayName: Docker_Build_Push_'$(Build.BuildNumber)'
  inputs:
    containerRegistry: 'dockerhub_login'
    repository: 'dockernaveensddp/azuredocker'
    command: 'buildAndPush'
    Dockerfile: '**/AzureDockerfile'
    addPipelineData: false
    addBaseImageData: false
- task: Bash@3
  displayName: Tagging_Image_for_Build_'$(Build.BuildNumber)'
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Tagging Images'
      docker tag dockernaveensddp/azuredocker:'$(Build.BuildNumber)' 240635294677.dkr.ecr.us-east-1.amazonaws.com/automation:latest
      echo "Tagging Completed"

- task: AzureWebAppContainer@1
  azureSubscription: 'Free Trial(f6d6363e-7586-4d2e-a1ba-44c368d411fa)'
    appName: 'docker-app-jabil'
    containers: 'dockernaveensddp/azuredocker:120'

- task: ECRPushImage@1
  inputs:
    awsCredentials: 'AWS_CREDENTIALS'
    regionName: 'us-east-1'
    imageSource: 'imagename'
    repositoryName: '240635294677.dkr.ecr.us-east-1.amazonaws.com/automation:'$(Build.BuildNumber)'

-